apiVersion: apps/v1
kind: Deployment
metadata:
  name: raghavssh-1626093
  labels:
    app: springbootssh
spec:
  replicas: 1
  selector:
       matchLabels:
         app: springbootssh
  template:
    metadata:
      name: springbootssh
      labels:
        app: springbootssh
    spec:
      containers:
      - name: springbootssh
        image: rgdocker2213/spring_test
        resources:
          limits:
            memory: 1Gi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.25"
  selector:
    matchLabels:
      app: springbootssh

---

apiVersion: v1
kind: Service
metadata:
  name: springbootssh
spec:
  selector:
    app: springbootssh
  ports:
    - port: 8080
  type: LoadBalancer
